### ISSUE TITLE
OCR识别图片文字

### ISSUE THREAD

**Issue by yion2019** [AlmightyDmg/my-spring-boot#1]
请问生成双层PDF的时候，OCR识别的JSON是要保证文字的格式和图片重叠吗？有没有OCR识别图片文字的案例呢？我看到代码中缺失了OCR识别的部分

**Comment by AlmightyDmg** [comment]
OCR 识别文字之后，识别的结果会带有文字所在位置坐标的，这样能够保证文字和图片的位置基本重合（生成双层pdf的时候需要进行微调）

目前 OCR 识别的案例是没有的，因为是调用的第三方付费服务，目前比较常见的OCR识别服务提供商有腾讯和科大讯飞，你可以去了解一下

**Comment by yion2019** [comment]
感谢楼主的回复，再请教下， 保证文字和图片的位置基本重合是双层PDF的必要条件吗？如果文字和图片不重叠，是无法产生双层，还是展示的时候错位。我自己尝试了一下写入了文字，但是在最后产生的PDF文件中只有图片，没有文字层。

**Comment by AlmightyDmg** [comment]
不保证重合也能够合成双层PDF，只不过展示的时候会出现错位。
合成双层PDF的最基本原理就是将文字添加到PDF上，然后再通过其他一些调整（例如文字位置，文字颜色，文字透明度，文字在pdf文字的上方或者下方等）来达到双层PDF的效果

**Comment by AlmightyDmg** [comment]
close
